version: '3.8'

services:
  discord-bot:
    build: .
    container_name: 9bots-discord-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      # Persist data directory
      - ./data:/app/data
      # Persist logs
      - ./logs:/app/logs
    networks:
      - bot-network
    # Uncomment if you need to expose ports for health checks
    # ports:
    #   - "3000:3000"

networks:
  bot-network:
    driver: bridge
